### ISSUE TITLE
[MM8] Fleetfingers does not work with GM Bow

### ISSUE THREAD

**Issue by Yami-an** [GrayFace/Misc#12]
The artifact Fleetfingers (+8 to Disarm Trap, Bow, and Armsmaster skills) does not add to bow damage when the character has GM bow. The bonus from normal and expert (attack and recovery) works as expected. The skill is shown as having +8 bonus. 

Edit: This also applies to other items that increase the bow skill (Tournament Bow, Longseeker).

**Comment by GrayFace** [comment]
fixed
