### ISSUE TITLE
Messed Player.Inventory

### ISSUE THREAD

**Issue by cthscr** [GrayFace/Misc#13]
MM7 + MM7Patch only: player's inventory suddenly got one full line linked to cells of previous line; later in game another one line got similar linking. Savegame (Party[2] has problematic inventory, leading to the game crash for original reporter): https://cdn.discordapp.com/attachments/845393451893653535/845393476346183690/save000.mm7

Merge has similar issue reported at https://gitlab.com/templayer/mmmerge/-/issues/223, was considered to be Merge fault initially but now I'm not so sure.

**Comment by GrayFace** [comment]
Upcoming patch version will fix such issues once and for all.
