### ISSUE TITLE
MM8Patch 2.5: DisableHooks does not disable certain hooks

### ISSUE THREAD

**Issue by cthscr** [GrayFace/Misc#16]
MM8Patch 2.5.5, previous versions might be affected as well.

mm8.ini line: `DisableHooks=44D96C,44DD9A,4541C9,47DA26,47DAA8,497A69`

Only hook at 0x44DD9A becomes disabled, all other are present in running code (viewed by OllyDbg).

All hooks are from MMCommon/MMHooks.pas. 0x44DD9A is the only hook from Hooks, other are from HooksCommon.

Suspicious place is MMCommon.pas CheckHooks() with its line `while hk[i].p <> 0 do` - there are previous hooks that aren't used for MM8 therefore legally have pointer equal to 0.

**Comment by GrayFace** [comment]
Thanks, fixed.
