### ISSUE TITLE
MM8Patch: CheckChestArtifact() boundary check missed

### ISSUE THREAD

**Issue by cthscr** [GrayFace/Misc#17]
In condition `if i >= _ArtifactsFoundCount^ then` of procedure CheckChestArtifact() `i` should be checked for being not lower than 0 also.

(It somehow became 0xDBDBD9E7 here. With eax (item pointer?) being 0xD9F28A6)

**Comment by GrayFace** [comment]
Does MMerge increase chests limit or something? Does it change 0x41F2A5? That bug will have more consequences than just this place.

**Comment by cthscr** [comment]
> Does MMerge increase chests limit or something?

No, as far as I can tell.

> Does it change 0x41F2A5?

No.

I don't expect that boundary check to fix Merge crashes, but jge (since variable is signed) after subtraction required it to be checked against 0. I just expect me to forget about this part soon.

**Comment by cthscr** [comment]
Speaking of crashes, first one is happened when you start a new game through RefillOdmHook. [esp+12] is 0x0D9D0010.

**Comment by GrayFace** [comment]
Does MMMerge introduce a special condition for items?
Send me a save where this happens.

**Comment by cthscr** [comment]
> Does MMMerge introduce a special condition for items?

No, as far as I can tell.

> Send me a save where this happens.

Attached to https://gitlab.com/templayer/mmmerge/-/issues/824

**Comment by GrayFace** [comment]
Pls also send me out01.odm, I don't have up-to-date Merge installed

**Comment by cthscr** [comment]
https://gitlab.com/cthscr/mmmerge/-/raw/7bb141688d8280565bb964fba33fc2f5ef68e5df/Data/revamp_mm8.games.lod?inline=false

I've checked against non-modified out01.odm - crash doesn't happen. I've checked other modified maps (of that lod) - some of them cause game to crash (out04, out08), some don't (out06). Map out06 was added last (if that matters).

**Comment by cthscr** [comment]
Non-modified maps: https://drive.google.com/file/d/1opcmzYJfdIPE2Or_JbdFQS-9I33Q4tHE/view?usp=sharing

**Comment by GrayFace** [comment]
Interesting. I'd also like to see the games.lod.

**Comment by cthscr** [comment]
> I'd also like to see the games.lod.

It's vanilla MM8's one. No map used.

**Comment by cthscr** [comment]
md5sums of games.lod and mm8.games.lod are the same.

**Comment by GrayFace** [comment]
Oh, I see what happens. I'll fix it in patch.

**Comment by cthscr** [comment]
Still (patch 2.5.6) have random (not 100% reproducible) crashes at the same point when accessing map out04.odm (regular game and editor, both from previously saved game; no hooks disabled).

```
Time: 21.02.2022 19:54:38 (21.02.2022 16:54:38 UTC)
Windows Version 5.1 Service Pack 3

Exception EAccessViolation in module MM8patch.dll at 00042DF2.
Access violation at address 03302DF2 in module 'MM8patch.dll'. Read of address AAC8AE9E.

Function Calls:

03302DF2 | C:\Games\Might and Magic 678 Revamp\MM8patch.dll + 42DF2
03302E3A ? C:\Games\Might and Magic 678 Revamp\MM8patch.dll + 42E3A
03302E50 ? C:\Games\Might and Magic 678 Revamp\MM8patch.dll + 42E50
0047DAA8 ? C:\Games\Might and Magic 678 Revamp\mm8.exe + 7DAA8
...

Registers:

EAX = AAC8AE9E
EBX = 005878D8
ECX = 00000001
EDX = 9D2C9D04
ESI = 006CEBD0
EDI = 000003C8
EBP = 0019FC28
ESP = 0019F064
```

**Comment by GrayFace** [comment]
No way to easily deal with such saves on my end. Either disable the hooks at 497A69 and 47DAA8 temporarily when entering the location 1st time or copy the proper .ddm to the save file.

**Comment by cthscr** [comment]
Thanks, all that I needed was to confirm it is indeed save related problem.
