### ISSUE TITLE
original italian version => "some files are missing, please reinstall"

### ISSUE THREAD

**Issue by loreb** [GrayFace/Misc#18]
I'm afraid I don't play mm8 that much so this is a veeeery late bug report - I was *sure* I had a previous install that worked, but apparently even version 2.1 (the oldest I could find) installs correctly and then refuses to run with that popup.

The problem seems to be that English{D,T}.lod is hardcoded somewhere in mm8.exe after installing the patch while I have data\Italian{D,T}.lod; symlinking those two files works on linux+wine, making copies works on windows.

The Italian versions of mm6/mm7 are not affected.

If for any reason fixing that turns out to be a pain just adding a warning would be 100% enough.

**Comment by GrayFace** [comment]
Registry value "language_file" under HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\New World Computing\Might and Magic Day of the Destroyer\1.0 defines this. You've probably installed it on another system and now run it from a folder, that's why it got set to "english" rather than "italian".

**Comment by loreb** [comment]
Just FYI I installed it on a system that had the 678 merge installed - renamed the merge directory, ran the vanilla mm8 installer, installed the patch (to see if it was a linux problem or not).
Anyway thank you & sorry for the bogus report.
