### ISSUE TITLE
mm7 patch 2.3.1 statusbar scale

### ISSUE THREAD

**Issue by aniserg** [GrayFace/Misc#5]
Привет!
При значении StatusbarScale=0.5 и ниже начинаются проблемы с npc, у которых нет диалогов. Их приветствие перестает отображатся, вместо него тоненькая полоска. Плюс сама statusbar при значении 0.4 выглядит криво.

**Comment by GrayFace** [comment]
Уменьшение интерфейса меньше изначального из игры не поддерживается.
