### ISSUE TITLE
mm7.ini options

### ISSUE THREAD

**Issue by aniserg** [GrayFace/Misc#6]
Можно ли добавить в readme или в mm7.ini все опции с описанием?
При удалении mm7.ini создается новый файл, но в нем отсутствуют многие опции.
Непонятно, что некоторые опции делают, непонятно, в каких рамках их можно менять.
Спасибо!

**Comment by GrayFace** [comment]
Все - нет. Опций, которые вряд ли надо будет менять, в нём специально нет. Описания будут.
