### ISSUE TITLE
Can't load file error MM8

### ISSUE THREAD

**Issue by MxyL** [GrayFace/Misc#8]
Hello

````
Can't load file! in file: d:\mm7Src\MM8\MMVIII\Code\Odmap.cpp at line number: 561
````

Getting this error when I use the MM8 patch. Happens immediately when I try to start the game.
I'm running it from the original disk. Does the patch work with the original disk or does it have to be from GOG?

MM7 from original disk worked fine so I was hoping it would work for 8 as well.

**Comment by GrayFace** [comment]
Yes it does. Send/attach the ErrorLog.txt file from game folder.

**Comment by MxyL** [comment]
[ErrorLog.txt](https://github.com/GrayFace/Misc/files/5080920/ErrorLog.txt)

Here's a copy of the error log.
Thanks for the help

**Comment by MxyL** [comment]
Just wondering if there's been any updates on this

**Comment by GrayFace** [comment]
Corrupt games.lod archive. Try reinstalling.
