### ISSUE TITLE
[GrayFace MM8 Patch] Character takes melee hits when monsters fight each other

### ISSUE THREAD

**Issue by andreyboytsov** [GrayFace/Misc#9]
The bug from very old times. Especially annoying in solo play, but can cause problems for any party too.

Reproduction:
- Monsters fight 2 vs 1.
- Two dealing a killing blow simultaneously.

Result: One hit goes to kill a monster, another goes to you, including bad effects.
Seems to happen when you are the next target of the monsters.
Just to clarify - monsters can be very far away from you, and still you get melee hits from them.

Exists in MM7, MM8, and MM678 merge. In MM6 monsters do not fight each other anyway.

See https://gitlab.com/templayer/mmmerge/-/issues/101

**Comment by GrayFace** [comment]
fixed
